### ISSUE TITLE
URL Redirect works fine on Android but not on iOS.

### ISSUE THREAD

**Issue by nicolasvac** [MaikuB/flutter_appauth#103]
Hello @MaikuB, i do have a problem with the app which i cannot figure it out.
Basically, my app has 3 different flavors, configured correctly on both Android and iOS.
Every build on Android works fine, the problem comes with iOS. It opens the page, but the ://oauthredirect never works.

<img width="730" alt="Schermata 2020-04-14 alle 13 04 45" src="https://user-images.githubusercontent.com/45635090/79218442-b5c08d00-7e50-11ea-8b3f-e23c6e891b7b.png">

<img width="468" alt="Schermata 2020-04-14 alle 13 05 33" src="https://user-images.githubusercontent.com/45635090/79218635-0506bd80-7e51-11ea-8444-b1e3c45a70bb.png">

in iOS i get strange webview logs but i guess is just part of the webview system.
Could you help me figure this out ?

Note that the endpoint on both Android and iOS is the same, so its not an endpoint problem.
Thanks

**Comment by MaikuB** [comment]
I have no knowledge your app so no. I can only guess you have a configuration issue. If you're after in-depth help (which is what it sounds like will be needed), please look at using one of the sites listed [here](https://flutter.dev/community)

**Comment by nicolasvac** [comment]
Just to be sure, is there something wrong in the config i posted up top ?

**Comment by MaikuB** [comment]
You appear to have the right keys though but whether or not the values are correct, I don't know

**Comment by bravelocation** [comment]
I'm having exactly the same issue - the example code pointing to my server works perfectly in Android, but appears to hang in iOS waiting to open the redirect URL.

@nicolasvac Did you find a solution?

Thanks
John

**Comment by nicolasvac** [comment]
@bravelocation No i did not.
@MaikuB are you sure your code works with multiple flavors ?

**Comment by MaikuB** [comment]
I haven't tested this with flavours but it shouldn't be relevant as it comes down to configuration so you need to make sure that the info.plist gets updated with the right value. Have you checked that? Also have you checked that it works when you manually put in the correct scheme?

**Comment by bravelocation** [comment]
FYI I fixed my issue - as @MaikuB says it was a configuration issue.

Turns out Azure B2C was adding an extra / on to the redirect URL, so in AppAuth it was saying the redirectURL I passed in was a mismatch

e.g. my redirectURL parameter was com.xxx.yyy://oauthredirect but what was coming back from Azure B2C was com.xxx.yyy://oauthredirect/?state=nnn i.e. an extra slash in the path of the URL.

@nicolasvac Hope that fix might work for you, and @MaikuB thanks for your help, and your useful library

**Comment by dwhiteddsoft** [comment]
so what did you change? Did you change the redirect URL in the code, the scheme in info.plist, or something on B2C side?

**Comment by bravelocation** [comment]
@dwhiteddsoft if that question was for me, as I said I changed the redirectUrl parameter to have an extra slash on the end in my Flutter code. 

This then matched the path part of the URL coming back from B2C. 

I had to debug the underlying AppAuth Objective-C code to figure out the “matching URL” code in there was not matching, but also not throwing an exception

**Comment by dwhiteddsoft** [comment]
I wrote a blog post on making it work with Azure B2C across both platforms https://www.detroitdave.dev/2020/04/simple-azure-b2c-flutter.html

**Comment by nicolasvac** [comment]
Hello @MaikuB. We did not fix our problem. We will be glad if we could contact you for a consultant with payed hours. My email is: nicolas.vaccari@web2life.it
Please contact me asap if you are interest. Thanks!

**Comment by MaikuB** [comment]
@nicolasvac thanks for the offer and I appreciate that you did do so. Unfortunately I don't think this is something I can do at the moment due to other other commitments. Furthermore, I don't think our timezones line up (I'm based in Sydney, Australia)

**Comment by nicolasvac** [comment]
Hi everyone. I'm glad to say that the issue has been fixed. After trying everything, i decided to look at the source and started investigating on the ADFS Windows Server. Turns out that ADFS adds a trailing slash at the end, so it doest not only affect Azure B2C instances, but also all the Microsoft Windows ADFS Servers. 
@MaikuB cool tip: You could be adding a note on the README for iOS on this.
But also, this doesnt explain why on Android it works and on the iOS version does not.
Apparently the iOS version strips out the /, while Android acquires it just fine. Is there anything related with your framework that needs to be fixed for this ?

**Comment by MaikuB** [comment]
I didn't build the framework, the plugin is a wrapper for existing native SDKs

**Comment by MaikuB** [comment]
Closing this as it's a difference in the behaviour of the native SDKs, which is out of my control

**Comment by listerp** [comment]
@nicolasvac how did you get it to work on Android? I had no issues on iOS but Android doesn't work for me.

**Comment by bryanCancelWT** [comment]
@listerp search for my comments on issues within this repo
I have the answer to that.... if you still need it after 2 years...

**Comment by bryanCancelWT** [comment]
@elemental21 I ended up having to use that as well
no idea where it comes from
all I know is that it works

**Comment by elemental21** [comment]
@bryanCancelWT  We found this yesterday. Has reference to endpoints that are similar but not quite the same. One of the bullets says "Remove /te if it exists in the URL.". Which we tried and that also works with iOS and Android. I'm still unsure where this all comes from but a little closer:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin

![image](https://user-images.githubusercontent.com/7585464/168289156-6c5ee277-8c3f-44b6-9c35-c4b790da4127.png)
