### ISSUE TITLE
ios, no activity of the plugin after redirection

### ISSUE THREAD

**Issue by thomas-topway-it** [MaikuB/flutter_appauth#223]
The plugin seems to be working correctly on ios, however after redirection the function 
```
final AuthorizationTokenResponse result = await appAuth.authorizeAndExchangeCode(
                    AuthorizationTokenRequest(
```

does not produce any output, also enclosing it within a ```try``` closure, as if the flow is interrupted.
Do you have any hint how to fix this ?
thanks
(Thomas)

**Comment by Nealsoni00** [comment]
I have the same issue on iOS, no result returned after a successful login and browser window closing. Android works fine. Any ideas on what to do to intercept the URL redirect? I've added the correct url to the `URL Schemes` in `info.plist`.

**Comment by thomas-topway-it** [comment]
@Nealsoni00, thanks a lot for the suggestion about android, I will check it later.
Regarding ios, we have solved using a redirect uri like
```
msauth://com.appname.app/flutter_appauth
```

and registering it under "Mobile and desktop applications" in the azure portal
It works

**Comment by RCSandberg** [comment]
Following up with same problem as @Nealsoni00 seems to have.

After calling ```authorizeAndExchangeCode()```, Safari opens a tab as it should, authentication is successful and the browser is closed as expected. But when debugging no result is produced and nothing is catched with enclosing:
```
try {
 ...authorizeAndExchangeCode(...)
} catch (e) {
}
```
I've tried trouble shooting it and when debugging I end up with getting no response from:
```
final Map<dynamic, dynamic>? result = await _channel.invokeMethod('authorizeAndExchangeCode', request.toMap());
```

I cannot find anything that failes in the toMap() method.

_CFBundleUrlSchemes_ is set in Info.plist to something like _com.company.myapp_, the redirectUrl is then set to _com.company.myapp://login-callback_

Any hints on how to continue the trouble shooting?

**Comment by Nealsoni00** [comment]
@thomas-topway-it  it appears like the redirect URI is generated on the azure portal based on the bundle identifier. What did you input there for the link `msauth://com.appname.app/flutter_appauth` to work? 

![image](https://user-images.githubusercontent.com/7013191/125664600-e2ceb923-1643-4ad3-971b-c5866cb8981a.png)

**Comment by thomas-topway-it** [comment]
you can add it directly on the manifest

**Comment by Nealsoni00** [comment]
@thomas-topway-it Got it! Thank you! 

For other users looking to solve this, I went into the azure console and add a custom `Mobile and desktop applications` redirect uri. 

![image](https://user-images.githubusercontent.com/7013191/125679269-65360550-ad60-43c2-803f-805e7133321b.png)

Then I had to add that URI to the `URL Schemes` in the `Info.plist` and it worked. 

The default iOS redirect uri provided by azure for iOS applications did not work.

**Comment by MaikuB** [comment]
Looks like this has been solved so will close the issue

**Comment by Nealsoni00** [comment]
BTW the app was rejected on submitting to the store since URLs on iOS can't start with `msauth://` and rather have to start with `com.company.app`. However, removing it from URL Schemes on the iOS app's `Info.plist` it still for some reason works in production when released to the store.

**Comment by mvukojicic** [comment]
Hey guys, I've run into the same problem, but none of these helped me, after entering credentials for login, I don't receive a token, and actually, nothing happens. I have tried solutions with different custom redirect URIs, which are still the same. Please any ideas on how to solve this?

**Comment by ma-vai** [comment]
> Hey guys, I've run into the same problem, but none of these helped me, after entering credentials for login, I don't receive a token, and actually, nothing happens. I have tried solutions with different custom redirect URIs, which are still the same. Please any ideas on how to solve this?

I am having the same issue as well. I have created a new issue here: https://github.com/MaikuB/flutter_appauth/issues/457
